// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
// #if canImport(keedavault_coreFFI)
// import keedavault_coreFFI
// #endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_keedavault_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_keedavault_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureKeedavaultCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol VaultProtocol: AnyObject, Sendable {
    
    func addEntry(entry: Entry) throws  -> String
    
    func addGroup(group: Group) throws  -> String
    
    func deleteEntry(id: String) throws 
    
    func deleteGroup(id: String) throws 
    
    func emptyRecycleBin() throws 
    
    func filterByTag(tag: String) throws  -> [Entry]
    
    func getEntries() throws  -> [Entry]
    
    func getEntry(id: String) throws  -> Entry
    
    func getFavorites() throws  -> [Entry]
    
    func getGroups() throws  -> [Group]
    
    /**
     * Check if vault is locked
     */
    func isLocked()  -> Bool
    
    /**
     * Lock the vault
     */
    func lock() throws 
    
    func permanentlyDeleteEntry(id: String) throws 
    
    func permanentlyDeleteGroup(id: String) throws 
    
    /**
     * Save the vault
     */
    func save() throws 
    
    func searchEntries(query: String) throws  -> [Entry]
    
    func updateEntry(id: String, entry: Entry) throws 
    
    func updateGroup(id: String, group: Group) throws 
    
}
open class Vault: VaultProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_keedavault_core_fn_clone_vault(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_keedavault_core_fn_free_vault(handle, $0) }
    }

    

    
open func addEntry(entry: Entry)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_add_entry(
            self.uniffiCloneHandle(),
        FfiConverterTypeEntry_lower(entry),$0
    )
})
}
    
open func addGroup(group: Group)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_add_group(
            self.uniffiCloneHandle(),
        FfiConverterTypeGroup_lower(group),$0
    )
})
}
    
open func deleteEntry(id: String)throws   {try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_delete_entry(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
open func deleteGroup(id: String)throws   {try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_delete_group(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
open func emptyRecycleBin()throws   {try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_empty_recycle_bin(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func filterByTag(tag: String)throws  -> [Entry]  {
    return try  FfiConverterSequenceTypeEntry.lift(try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_filter_by_tag(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(tag),$0
    )
})
}
    
open func getEntries()throws  -> [Entry]  {
    return try  FfiConverterSequenceTypeEntry.lift(try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_get_entries(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getEntry(id: String)throws  -> Entry  {
    return try  FfiConverterTypeEntry_lift(try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_get_entry(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
})
}
    
open func getFavorites()throws  -> [Entry]  {
    return try  FfiConverterSequenceTypeEntry.lift(try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_get_favorites(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getGroups()throws  -> [Group]  {
    return try  FfiConverterSequenceTypeGroup.lift(try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_get_groups(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Check if vault is locked
     */
open func isLocked() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_keedavault_core_fn_method_vault_is_locked(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Lock the vault
     */
open func lock()throws   {try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_lock(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func permanentlyDeleteEntry(id: String)throws   {try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_permanently_delete_entry(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
open func permanentlyDeleteGroup(id: String)throws   {try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_permanently_delete_group(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),$0
    )
}
}
    
    /**
     * Save the vault
     */
open func save()throws   {try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_save(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func searchEntries(query: String)throws  -> [Entry]  {
    return try  FfiConverterSequenceTypeEntry.lift(try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_search_entries(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(query),$0
    )
})
}
    
open func updateEntry(id: String, entry: Entry)throws   {try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_update_entry(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterTypeEntry_lower(entry),$0
    )
}
}
    
open func updateGroup(id: String, group: Group)throws   {try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_method_vault_update_group(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(id),
        FfiConverterTypeGroup_lower(group),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVault: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Vault

    public static func lift(_ handle: UInt64) throws -> Vault {
        return Vault(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Vault) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Vault {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Vault, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVault_lift(_ handle: UInt64) throws -> Vault {
    return try FfiConverterTypeVault.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVault_lower(_ value: Vault) -> UInt64 {
    return FfiConverterTypeVault.lower(value)
}




/**
 * Custom field
 */
public struct CustomField: Equatable, Hashable {
    public var key: String
    public var value: String
    public var protected: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String, value: String, protected: Bool) {
        self.key = key
        self.value = value
        self.protected = protected
    }

    
}

#if compiler(>=6)
extension CustomField: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCustomField: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CustomField {
        return
            try CustomField(
                key: FfiConverterString.read(from: &buf), 
                value: FfiConverterString.read(from: &buf), 
                protected: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: CustomField, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.value, into: &buf)
        FfiConverterBool.write(value.protected, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCustomField_lift(_ buf: RustBuffer) throws -> CustomField {
    return try FfiConverterTypeCustomField.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCustomField_lower(_ value: CustomField) -> RustBuffer {
    return FfiConverterTypeCustomField.lower(value)
}


/**
 * Entry data structure for UniFFI (simplified with i64 timestamps)
 */
public struct Entry: Equatable, Hashable {
    public var id: String
    public var groupId: String
    public var title: String
    public var username: String
    public var password: String
    public var url: String
    public var notes: String
    public var tags: [String]
    public var totpSecret: String?
    public var customFields: [CustomField]
    public var createdAt: Int64
    public var modifiedAt: Int64
    public var accessedAt: Int64
    public var expiresAt: Int64?
    public var isFavorite: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, groupId: String, title: String, username: String, password: String, url: String, notes: String, tags: [String], totpSecret: String?, customFields: [CustomField], createdAt: Int64, modifiedAt: Int64, accessedAt: Int64, expiresAt: Int64?, isFavorite: Bool) {
        self.id = id
        self.groupId = groupId
        self.title = title
        self.username = username
        self.password = password
        self.url = url
        self.notes = notes
        self.tags = tags
        self.totpSecret = totpSecret
        self.customFields = customFields
        self.createdAt = createdAt
        self.modifiedAt = modifiedAt
        self.accessedAt = accessedAt
        self.expiresAt = expiresAt
        self.isFavorite = isFavorite
    }

    
}

#if compiler(>=6)
extension Entry: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Entry {
        return
            try Entry(
                id: FfiConverterString.read(from: &buf), 
                groupId: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                username: FfiConverterString.read(from: &buf), 
                password: FfiConverterString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf), 
                notes: FfiConverterString.read(from: &buf), 
                tags: FfiConverterSequenceString.read(from: &buf), 
                totpSecret: FfiConverterOptionString.read(from: &buf), 
                customFields: FfiConverterSequenceTypeCustomField.read(from: &buf), 
                createdAt: FfiConverterInt64.read(from: &buf), 
                modifiedAt: FfiConverterInt64.read(from: &buf), 
                accessedAt: FfiConverterInt64.read(from: &buf), 
                expiresAt: FfiConverterOptionInt64.read(from: &buf), 
                isFavorite: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Entry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.groupId, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.username, into: &buf)
        FfiConverterString.write(value.password, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.notes, into: &buf)
        FfiConverterSequenceString.write(value.tags, into: &buf)
        FfiConverterOptionString.write(value.totpSecret, into: &buf)
        FfiConverterSequenceTypeCustomField.write(value.customFields, into: &buf)
        FfiConverterInt64.write(value.createdAt, into: &buf)
        FfiConverterInt64.write(value.modifiedAt, into: &buf)
        FfiConverterInt64.write(value.accessedAt, into: &buf)
        FfiConverterOptionInt64.write(value.expiresAt, into: &buf)
        FfiConverterBool.write(value.isFavorite, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntry_lift(_ buf: RustBuffer) throws -> Entry {
    return try FfiConverterTypeEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntry_lower(_ value: Entry) -> RustBuffer {
    return FfiConverterTypeEntry.lower(value)
}


/**
 * Group data structure for UniFFI
 */
public struct Group: Equatable, Hashable {
    public var id: String
    public var parentId: String?
    public var name: String
    public var iconId: UInt32
    public var notes: String
    public var isRecycleBin: Bool
    public var isExpanded: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, parentId: String?, name: String, iconId: UInt32, notes: String, isRecycleBin: Bool, isExpanded: Bool) {
        self.id = id
        self.parentId = parentId
        self.name = name
        self.iconId = iconId
        self.notes = notes
        self.isRecycleBin = isRecycleBin
        self.isExpanded = isExpanded
    }

    
}

#if compiler(>=6)
extension Group: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGroup: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Group {
        return
            try Group(
                id: FfiConverterString.read(from: &buf), 
                parentId: FfiConverterOptionString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                iconId: FfiConverterUInt32.read(from: &buf), 
                notes: FfiConverterString.read(from: &buf), 
                isRecycleBin: FfiConverterBool.read(from: &buf), 
                isExpanded: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Group, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.parentId, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt32.write(value.iconId, into: &buf)
        FfiConverterString.write(value.notes, into: &buf)
        FfiConverterBool.write(value.isRecycleBin, into: &buf)
        FfiConverterBool.write(value.isExpanded, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGroup_lift(_ buf: RustBuffer) throws -> Group {
    return try FfiConverterTypeGroup.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGroup_lower(_ value: Group) -> RustBuffer {
    return FfiConverterTypeGroup.lower(value)
}


/**
 * Vault configuration
 */
public struct VaultConfig: Equatable, Hashable {
    public var kdfIterations: UInt64
    public var argon2Memory: UInt64
    public var argon2Parallelism: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kdfIterations: UInt64, argon2Memory: UInt64, argon2Parallelism: UInt32) {
        self.kdfIterations = kdfIterations
        self.argon2Memory = argon2Memory
        self.argon2Parallelism = argon2Parallelism
    }

    
}

#if compiler(>=6)
extension VaultConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaultConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaultConfig {
        return
            try VaultConfig(
                kdfIterations: FfiConverterUInt64.read(from: &buf), 
                argon2Memory: FfiConverterUInt64.read(from: &buf), 
                argon2Parallelism: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: VaultConfig, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.kdfIterations, into: &buf)
        FfiConverterUInt64.write(value.argon2Memory, into: &buf)
        FfiConverterUInt32.write(value.argon2Parallelism, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaultConfig_lift(_ buf: RustBuffer) throws -> VaultConfig {
    return try FfiConverterTypeVaultConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaultConfig_lower(_ value: VaultConfig) -> RustBuffer {
    return FfiConverterTypeVaultConfig.lower(value)
}


/**
 * Error type for UniFFI
 */
public enum VaultError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case VaultLocked
    case InvalidPassword
    case EntryNotFound
    case GroupNotFound
    case InvalidEntry
    case EncryptionError
    case DecryptionError
    case IoError
    case SerializationError
    case KeePassError
    case Unknown

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension VaultError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaultError: FfiConverterRustBuffer {
    typealias SwiftType = VaultError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaultError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .VaultLocked
        case 2: return .InvalidPassword
        case 3: return .EntryNotFound
        case 4: return .GroupNotFound
        case 5: return .InvalidEntry
        case 6: return .EncryptionError
        case 7: return .DecryptionError
        case 8: return .IoError
        case 9: return .SerializationError
        case 10: return .KeePassError
        case 11: return .Unknown

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: VaultError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .VaultLocked:
            writeInt(&buf, Int32(1))
        
        
        case .InvalidPassword:
            writeInt(&buf, Int32(2))
        
        
        case .EntryNotFound:
            writeInt(&buf, Int32(3))
        
        
        case .GroupNotFound:
            writeInt(&buf, Int32(4))
        
        
        case .InvalidEntry:
            writeInt(&buf, Int32(5))
        
        
        case .EncryptionError:
            writeInt(&buf, Int32(6))
        
        
        case .DecryptionError:
            writeInt(&buf, Int32(7))
        
        
        case .IoError:
            writeInt(&buf, Int32(8))
        
        
        case .SerializationError:
            writeInt(&buf, Int32(9))
        
        
        case .KeePassError:
            writeInt(&buf, Int32(10))
        
        
        case .Unknown:
            writeInt(&buf, Int32(11))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaultError_lift(_ buf: RustBuffer) throws -> VaultError {
    return try FfiConverterTypeVaultError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaultError_lower(_ value: VaultError) -> RustBuffer {
    return FfiConverterTypeVaultError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCustomField: FfiConverterRustBuffer {
    typealias SwiftType = [CustomField]

    public static func write(_ value: [CustomField], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCustomField.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CustomField] {
        let len: Int32 = try readInt(&buf)
        var seq = [CustomField]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCustomField.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeEntry: FfiConverterRustBuffer {
    typealias SwiftType = [Entry]

    public static func write(_ value: [Entry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Entry] {
        let len: Int32 = try readInt(&buf)
        var seq = [Entry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeGroup: FfiConverterRustBuffer {
    typealias SwiftType = [Group]

    public static func write(_ value: [Group], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeGroup.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Group] {
        let len: Int32 = try readInt(&buf)
        var seq = [Group]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeGroup.read(from: &buf))
        }
        return seq
    }
}
public func createVault(path: String, password: String, config: VaultConfig)throws  -> Vault  {
    return try  FfiConverterTypeVault_lift(try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_func_create_vault(
        FfiConverterString.lower(path),
        FfiConverterString.lower(password),
        FfiConverterTypeVaultConfig_lower(config),$0
    )
})
}
public func generateTotp(secret: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_func_generate_totp(
        FfiConverterString.lower(secret),$0
    )
})
}
public func getRemainingSeconds() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_keedavault_core_fn_func_get_remaining_seconds($0
    )
})
}
public func openVault(path: String, password: String)throws  -> Vault  {
    return try  FfiConverterTypeVault_lift(try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_func_open_vault(
        FfiConverterString.lower(path),
        FfiConverterString.lower(password),$0
    )
})
}
public func validateTotp(secret: String, code: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeVaultError_lift) {
    uniffi_keedavault_core_fn_func_validate_totp(
        FfiConverterString.lower(secret),
        FfiConverterString.lower(code),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_keedavault_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_keedavault_core_checksum_func_create_vault() != 41851) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_func_generate_totp() != 9391) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_func_get_remaining_seconds() != 31875) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_func_open_vault() != 10299) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_func_validate_totp() != 2558) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_add_entry() != 20382) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_add_group() != 45625) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_delete_entry() != 15965) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_delete_group() != 33546) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_empty_recycle_bin() != 31250) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_filter_by_tag() != 56375) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_get_entries() != 25553) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_get_entry() != 43767) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_get_favorites() != 25454) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_get_groups() != 46896) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_is_locked() != 53852) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_lock() != 8108) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_permanently_delete_entry() != 26181) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_permanently_delete_group() != 54312) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_save() != 54218) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_search_entries() != 17548) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_update_entry() != 24078) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_keedavault_core_checksum_method_vault_update_group() != 28251) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureKeedavaultCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all